### ISSUE TITLE
Checkpoint after multi-task training

### ISSUE THREAD

**Issue by ManasiPat** [justinphan3110/CoTexT#1]
Are you planning to provide the your checkpoint after multitask training for code summarization

**Comment by ManasiPat** [comment]
Are you planning to provide the your checkpoint after multitask training for code summarization

**Comment by ManasiPat** [comment]
I didn't want to close this issue

**Comment by justinphan3110** [comment]
Hi, we don't release checkpoints for fine-tune tasks. However, you can finetune the code summarization task based on the [public code](https://github.com/justinphan3110/CoTexT/blob/main/code_summarization/codesearchnet_2.ipynb) and pre-trained checkpoints.
