### ISSUE TITLE
Checkpoint of multi-task learning

### ISSUE THREAD

**Issue by ManasiPat** [justinphan3110/CoTexT#2]
Are you planning to provide the your checkpoint after multitask training for code summarization

**Comment by justinphan3110** [comment]
Hi, we don't release checkpoints for fine-tune tasks. However, you can finetune the code summarization task based on the [public code](https://github.com/justinphan3110/CoTexT/blob/main/code_summarization/codesearchnet_2.ipynb) and pre-trained checkpoints
