### ISSUE TITLE
Code Generation Task

### ISSUE THREAD

**Issue by JessicaLopezEspejel** [justinphan3110/CoTexT#3]
Hello! Are you planning to provide the checkpoints of code generation task?

**Comment by justinphan3110** [comment]
Hi, we don't release checkpoints for fine-tune tasks. However, you can finetune the code generation task based on the [public code](https://github.com/justinphan3110/CoTexT/blob/main/code_generation/CodeGenerationUni.ipynb) and pre-trained checkpoints
