### ISSUE TITLE
GCS permission

### ISSUE THREAD

**Issue by JessicaLopezEspejel** [justinphan3110/CoTexT#4]
Hello, can we have access to gs://t5_training/t5-data/code_data/codesearchnet/java/train.tsv ? To run the code the permission is denied.

**Comment by justinphan3110** [comment]
Hi,
the GCS URI should be gs://cotext/data/codesearchnet/java/train.tsv or gs://cotext/data/codesearchnet/java/train_encode.tsv

**Comment by JessicaLopezEspejel** [comment]
I tried both but neither works :/

**Comment by JessicaLopezEspejel** [comment]
Thank you so much. However, when I try to load the data is not possible. The code I am running is the following:

`train_files = []
train_files.extend(list(map(lambda x: x.strip(), subprocess.run(['gsutil', 'ls', f'gs://cotext/data/pretrain/python/python_train_pl_nl.tsv'], stdout=subprocess.PIPE).stdout.splitlines())))
  print(len(train_files))
`
The result is 0

It means it's not reading the data. In the permission sections of your bucket: https://console.cloud.google.com/storage/browser/cotext/data/pretrain/python;tab=permissions?prefix=&forceOnObjectsSortingFiltering=false

appears the following message: 

_Additional permissions are required to view the metadata for this bucket. Ask the bucket owner to grant you the "storage.buckets.get" and "storage.buckets.getIamPolicy" permissions (eg, they can assign your account the storage administrator IAM role)._

Do you have any suggestion? 

Thank you.

**Comment by heraclex12** [comment]
Hi @JessicaLopezEspejel

I have checked the bucket permission. And now you are able to run our code.
