### ISSUE TITLE
Checkpoints

### ISSUE THREAD

**Issue by JessicaLopezEspejel** [justinphan3110/CoTexT#5]
Hello!

I am running the following code: 

`FINETUNE_STEPS = 45000`
`BASE_PRETRAINED_DIR = "gs://cotext/cc/"  # JL`
`PRETRAINED_DIR = BASE_PRETRAINED_DIR`

`model.finetune(`
 `   mixture_or_task_name="all_mix",`
  `  pretrained_model_dir=PRETRAINED_DIR,`
 ` finetune_steps=FINETUNE_STEPS,`
`)`
I got the following error:

`Value error: No checkpoints found in the model directory: gs://cotext/cc/`

However, if instead of `BASE_PRETRAINED_DIR = "gs://cotext/cc/"` I used  `BASE_PRETRAINED_DIR = "BASE_PRETRAINED_DIR = "gs://t5-data/pretrained_models/base""` and the model does the fine-tuning. 

However, I want to do the fine-tuning on gs://cotext/cc/ (C4/CodeSearchNet) not on T5 base. I found the difference between both folders is the number of files. For example, in `gs://cotext/cc/` there are 4 files, and in `gs://t5-data/pretrained_models/base` there are 19 files. 

I guess there are some files are missing, but I am not sure about it. Can you help me? please

Thank you so much

**Comment by heraclex12** [comment]
Hi,

We provide all our CoText versions at 1200000 steps. So you should use `FINETUNE_STEPS=1200000` to finetune CoText models

**Comment by justinphan3110** [comment]
Hi, I have re-uploaded the model files to gs://cotext/cc/, it should works now

**Comment by JessicaLopezEspejel** [comment]
Thank you, it works.
